### PR TITLE
Force to use attributed text

### PR DESCRIPTION
**Pull request by vadymmarkov**
While testing I've discovered that setting style attributes via `UILabel.appearance()` doesn't always work as expected. That's why I've decided to add support of `NSAttributedString` that makes it even more customisable. Now it's possible to set any attributes you want both for title and text in any model.

### CODE REVIEW

**Comment by 3lvis** [comment]
Smart!

**Comment by 3lvis** [comment]
This looks like a good way to go, the idea was that we had some general way to style the title and the text without having to duplicate much. That's why we went for `appearance`.

**Comment by 3lvis** [comment]
I'm fine for going with this approach, looks quite good.

What do you think @zenangst?

**Comment by vadymmarkov** [comment]
I've done this because I wasn't able to change `UILabel` styles via our `appearance` methods while using this pod as a dependency in Objective C project. Then I've founds this https://gist.github.com/mattt/5135521 and seems like `UILabel` doesn't even customisable via `appearance`. But sometimes it works, like in Demo :smile: 

We also can make `titleLabel` and `textView` public, but I guess the approach with `attributeText` is better. But now I'm thinking that we should make them public anyway if we would like to update constraints...

**Comment by vadymmarkov** [comment]
As we discussed with @3lvis it's not necessary to make `views` public. Now it could be only just new methods to set title and text offsets.

**Comment by 3lvis** [comment]
:clap: 

:star2: :cake: :star2:

**Pull request merged**
